
# VALUES (("nombre",
#         "descripcion",
#         precio,
#         "Producto",
#         "Peluquería",
#         "imagen",
#         "thumbnail",
#         true,
#         "descripcionCorta"),
        
        
#         )


VALUES (("Shampoo Inforcer 300 ml L'Oreal",
        "Shampoo anti quiebre, fortificante con vitamina B6 y Biotina, reducción instantánea de la rotura del pelo, cabello más resistente y más fuerte.\nBeneficios: Fortalece el cabello, suaviza, facilita el peinado\nTipo de Pelo: Quebradizo o dañado\nAplicación: todo el cabello",
        990,
        "Producto",
        "Peluquería",
        "https://res.cloudinary.com/dhcdkw7os/image/upload/v1638048724/Productos/0000747_shampoo-inforcer-300-ml-loreal-professionnel_600_bt30zb.jpg",
        "https://res.cloudinary.com/dhcdkw7os/image/upload/v1638048724/Productos/0000747_shampoo-inforcer-300-ml-loreal-professionnel_600_bt30zb.jpg",
        true,
        "Shampoo anti quiebre"),
        ("Aceite Mythic Oil 100 ml L'Oreal",
        "Aceite de Argán nutritivo de uso profesional para todo tipo de cabello, protege y suaviza el pelo, textura ligera y fluida que facilita el secado.\nBeneficios: Protección, Brillo, Suavidad\nTipo de Pelo: todo tipo de cabello\nAplicación: Medios y largos",
        1800,
        "Producto",
        "Peluquería",
        "https://res.cloudinary.com/dhcdkw7os/image/upload/v1638048724/Productos/0000702_aceite-mythic-oil-100-ml-loreal-professionnel_notweq.jpg",
        "https://res.cloudinary.com/dhcdkw7os/image/upload/v1638048724/Productos/0000702_aceite-mythic-oil-100-ml-loreal-professionnel_notweq.jpg",
        true,
        "Aceite de Argán nutritivo"),
        ("Ampolla Pro Longer 15 ml L'Oreal",
        "Ampolla profesional para renovar las puntas de tu cabello en casa, hasta tu próxima visita al salón! La ampolla de Pro longer es un concentrado rellenador de puntas de un uso a la semana. Este tratamiento concentrado es ideal para cabellos largos con puntas finas y partidas o abiertas. Su formula altamente concentrada de FILLER-A100 y aminoácidos aporta fuerza y grosor duradero de manera inmediata. Estos componentes penetran en el núcleo de la fibra para engrosar y fortalecer las puntas, devolviendole la vida a los ultimos cm del cabello.",
        650,
        "Producto",
        "Peluquería",
        "https://res.cloudinary.com/dhcdkw7os/image/upload/v1638048723/Productos/0001796_ampolla-pro-longer-15-ml-loreal-professionnel_600_bw8byl.jpg",
        "https://res.cloudinary.com/dhcdkw7os/image/upload/v1638048723/Productos/0001796_ampolla-pro-longer-15-ml-loreal-professionnel_600_bw8byl.jpg",
        true,
        "Ampolla renovadora de puntas"),
        ("Acondicionador Blondifier 200 ml L'Oreal",
        "Acondicionador profesional para mantener un rubio perfecto en casa, hasta tu próxima visita al salón! Acondicionador enriquecido con extracto de Açai El ligero acondicioandor ayuda a mejorar el brillo natural del cabello rubio. Cabello instántaneamente más brillante, suave y fácil de desenredar de raíz a puntas.",
        980,
        "Producto",
        "Peluquería",
        "https://res.cloudinary.com/dhcdkw7os/image/upload/v1638048723/Productos/0001772_acondicionador-blondifier-para-rubios-loreal-pro-200-ml_600_zebghr.jpg",
        "https://res.cloudinary.com/dhcdkw7os/image/upload/v1638048723/Productos/0001772_acondicionador-blondifier-para-rubios-loreal-pro-200-ml_600_zebghr.jpg",
        true,
        "Acondicionador para cabellos rubios")
        )