"""empty message

Revision ID: 7321284a858d
Revises: ec0f94b034d0
Create Date: 2021-11-22 03:13:40.297883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7321284a858d'
down_revision = 'ec0f94b034d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrito_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrito_compras')
    # ### end Alembic commands ###
