"""empty message

Revision ID: ec0f94b034d0
Revises: fbd168e29570
Create Date: 2021-11-22 03:05:07.361865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0f94b034d0'
down_revision = 'fbd168e29570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('descripcionCorta', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'descripcionCorta')
    # ### end Alembic commands ###
